Park card
Erreses/trust_app pull request #25
Opened 2022-12-29 15:24 UTC by rapm94

2022-12-29 17:59 UTC, ratuozzo commented on lib/components/park-card/trust_park_card.dart
> +
Metele 3 parametros de entrada:

- El titulo
- Un dateTime (opcional)
- Un status (opcional)

Los parametros opcionales son porque hay algunas implementaciones que no muestran fecha ni status (puntos)

Esto puede cambiar cuando le metamos un modelo pero igual no creo que sea mucho

2022-12-29 18:01 UTC, ratuozzo requested changes
Metele 3 parametros de entrada:

El titulo
Un dateTime (opcional)
Un status (opcional)
Tambien dos para el texto de la derecha, uno opcional (el pequeño) y el otro si required

Los parametros opcionales son porque hay algunas implementaciones que no muestran fecha ni status (puntos) ni texto pequeño de la derecha

Esto puede cambiar cuando le metamos un modelo pero igual no creo que sea mucho

2022-12-30 17:34 UTC, ratuozzo commented on lib/components/park-card/trust_park_card.dart
> +      width: 365,
Aqui es mejor en vez de definir un width del container, poner `margin: const EdgeInsets.symmetric(horizontal: 20)` 
Lo que se quiere es que el container este separado de los bordes, si el tamaño de la pantalla crece se vera mas pequeño, y si es una pantalla muy pequeña dara overflow

2022-12-30 17:39 UTC, ratuozzo commented on lib/components/park-card/trust_park_card.dart
> +                    widget.title,
Si el titulo del parking es muy largo dara overflow, hay que hacer que pueda crecer hacia abajo el texto
En este caso puedes wrappear el text en un SizedBox y le pones el width, yo calcularia el witdth asi:
(Width de la pantalla) - (margin que te comente arriba) - (padding interno del card) - (width del cuadrado de la derecha).. Creo que poniendo solo el SizedBox haria que se expandiera hacia abajo el card si es muy largo el titulo.
En Dart puedes hacer `widget.title * 2` y te lo pone dos veces el texto

2022-12-30 17:40 UTC, ratuozzo requested changes
Mas cambiesinos

2022-12-30 20:46 UTC, rapm94 commented on lib/components/park-card/trust_park_card.dart
> +                    widget.title,
Okey no sabia

2022-12-30 21:21 UTC, ratuozzo approved these changes

2022-12-30 21:22 UTC, merged