20 create slide up overlay
Erreses/trust_app pull request #39
Opened 2023-01-04 11:39 UTC by rapm94

2023-01-04 18:21 UTC, rapm94 commented
Revisa ahi pue

2023-01-06 09:39 UTC, ratuozzo commented on lib/components/trust_bottom_sheet/trust_bottom_sheet.dart
> +import 'package:flutter/material.dart';
Esto en vez de ser un widget tiene que ser un .dart que solo tiene el metodo de `showCupertinoModalBottomSheet`

2023-01-06 09:39 UTC, ratuozzo commented on lib/components/instagram_campaign/InstagramCampaign.dart
> +class InstagramCampaign extends StatefulWidget {
Esto puede ser un stateless widget, siempre que se pueda hay que evitar los stateful

2023-01-06 09:41 UTC, ratuozzo commented on lib/components/instagram_campaign/InstagramCampaign.dart
> +
En esta clase es donde va el metodo estatico show, y cuando queramos mostrar el bottom sheet con esto hariamos `InstagramCampaign.show`

2023-01-06 09:41 UTC, ratuozzo requested changes
Cambios

2023-01-06 14:44 UTC, ratuozzo approved these changes

2023-01-06 14:44 UTC, merged