59 create vehicle screen
Erreses/trust_app pull request #62
Opened 2023-01-09 22:13 UTC by rapm94

2023-01-09 22:46 UTC, ratuozzo requested changes
No entendí lo del sliver por qué hace falta ahí?

2023-01-09 22:46 UTC, ratuozzo commented on lib/presentation/settings/vehicle/vehicles_screen.dart
> +      appBar: AppBar(
Tenemos un app bar que se llama trust app bar

2023-01-09 22:46 UTC, ratuozzo commented on lib/presentation/settings/vehicle/vehicles_screen.dart
> +            SliverAppBar(
Por qué es un sliver?

2023-01-09 23:22 UTC, rapm94 commented on lib/presentation/settings/vehicle/vehicles_screen.dart
> +            SliverAppBar(
hice sticky esa parte el sliver appbar pa que se mantenga el add aunque hagas scroll si quieres lo quito

2023-01-09 23:22 UTC, rapm94 commented on lib/presentation/settings/vehicle/vehicles_screen.dart
> +      appBar: AppBar(
Ah

2023-01-09 23:23 UTC, rapm94 commented on lib/presentation/settings/vehicle/vehicles_screen.dart
> +            SliverAppBar(
Avisame esto

2023-01-10 16:17 UTC, ratuozzo approved these changes

2023-01-10 16:17 UTC, merged